name: 'Release & Publish to NPM'

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Install the dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Initialize Git user
        run: |
          git config --global user.email "03balogun@gmail.com"
          git config --global user.name "Release God"
      - name: Initialize npm config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: End Message
        run: echo "Release process completed"
